[build]
  functions = "functions" # Specify the directory where your functions are stored
  publish = "public" # Specify the directory where your static files are located, if applicable

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
